### Importing the Needed Libraries

In [21]:
#!pip install pydotplus
import pandas as pd
import numpy as np
from matplotlib import pyplot

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import random
random.seed(0)

from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus

import utils

# First: Using Regression Decision Tree as the Dataset Indicates

### Getting the Dataset

In [22]:
Admission_Predict_Dataset=pd.read_csv('Admission_Predict.csv')
Admission_Predict_Dataset

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

### Splitting the Dataset into Features & Labels

In [23]:
features = Admission_Predict_Dataset.drop(['Chance of Admit','Serial No.'],axis=1)
labels = Admission_Predict_Dataset['Chance of Admit']

### Splitting the Dataset into Training, Testing, and Validation Data

In [24]:
features_train, features_validation_test, labels_train, labels_validation_test = train_test_split(
    features, labels, test_size=0.4, random_state=100)

In [25]:
features_validation, features_test, labels_validation, labels_test = train_test_split(
    features_validation_test, labels_validation_test, test_size=0.5, random_state=100)

In [26]:
print(len(features_train))
print(len(features_validation))
print(len(features_test))
print(len(labels_train))
print(len(labels_validation))
print(len(labels_test))

240
80
80
240
80
80

## Decision Tree (with max depth)

In [27]:
dt_regressor = DecisionTreeRegressor(max_depth=4)
dt_regressor.fit(features_train, labels_train)
reg_test_score=dt_regressor.score(features_test, labels_test)
reg_validation_score=dt_regressor.score(features_validation, labels_validation)
print(reg_test_score)
print(reg_validation_score)

0.6162559527402046
0.8497838914837949

### Building a Predictive System

In [28]:
# predict

print(dt_regressor.predict([[335,115,4,5,4.5,9,1]]))

print(dt_regressor.predict([[310,100,3,2,3,8,0]]))

[0.786875]
[0.554]

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [29]:
utils.display_tree(dt_regressor)

ModuleNotFoundError: No module named 'sklearn.externals.six'

## Decision Tree (without any restrictions)

In [30]:
dt_regressor2 = DecisionTreeRegressor()
dt_regressor2.fit(features_train, labels_train)
reg_test_score2=dt_regressor2.score(features_test, labels_test)
reg_validation_score2=dt_regressor2.score(features_validation, labels_validation)
print(reg_test_score2)
print(reg_validation_score2)

0.4334617549607487
0.7436553887676816

### Building a Predictive System

In [31]:
# predict

print(dt_regressor2.predict([[335,115,4,5,4.5,9,1]]))

print(dt_regressor2.predict([[310,100,3,2,3,8,0]]))

[0.81]
[0.62]

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [32]:
utils.display_tree(dt_regressor2)

ModuleNotFoundError: No module named 'sklearn.externals.six'

## Decision Tree (using squared error index)

In [33]:
dt_regressor3 = DecisionTreeRegressor(criterion='squared_error')  #{'absolute_error', 'friedman_mse', 'poisson', 'squared_error'}
dt_regressor3.fit(features_train, labels_train)
reg_test_score3=dt_regressor3.score(features_test, labels_test)
reg_validation_score3=dt_regressor3.score(features_validation, labels_validation)
print(reg_test_score3)
print(reg_validation_score3)

0.4076426036220965
0.7450287700996971

### Building a Predictive System

In [34]:
# predict

print(dt_regressor3.predict([[335,115,4,5,4.5,9,1]]))

print(dt_regressor3.predict([[310,100,3,2,3,8,0]]))

[0.81]
[0.63]

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [35]:
utils.display_tree(dt_regressor3)

ModuleNotFoundError: No module named 'sklearn.externals.six'

# Additional: Using XGBoost Regressor

In [36]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
import utils
import sklearn
from sklearn import tree
import matplotlib.pyplot as plt

In [37]:
#!pip install xgboost
import xgboost
from xgboost import XGBRegressor
xgboost_regressor = XGBRegressor(random_state=0,
                             n_estimators=3,
                             max_depth=2,
                             reg_lambda=0,
                             min_split_loss=1,
                             learning_rate=0.7)
xgboost_regressor.fit(features_train, labels_train)
xgboost_test_score=xgboost_regressor.score(features_test, labels_test)
xgboost_validation_score=xgboost_regressor.score(features_validation, labels_validation)
print(xgboost_test_score)
print(xgboost_validation_score)

0.36415016621998253
0.5496238077387825

In [38]:
xgboost_regressor.predict(features)

array([0.806308 , 0.806308 , 0.6627394, 0.806308 , 0.6627394, 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.6627394,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.806308 ,
       0.806308 , 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.806308 , 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.6627394,
       0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.6627394,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.806308 , 0.6627394,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.6627394, 0.806308 ,
       0.806308 , 0.6627394, 0.806308 , 0.806308 , 0.6627394, 0.806308 ,
       0.6627394, 0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.6627394,
       0.6627394, 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.6627394, 0.6627394, 0.806308 , 0.6627394,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 , 0.6627394, 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.6627394, 0.806308 , 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.806308 , 0.806308 , 0.6627394, 0.806308 , 0.806308 ,
       0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.806308 ,
       0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.6627394,
       0.806308 , 0.806308 , 0.6627394, 0.6627394, 0.6627394, 0.6627394,
       0.6627394, 0.6627394, 0.806308 , 0.806308 , 0.806308 , 0.806308 ,
       0.806308 , 0.806308 , 0.806308 , 0.806308 ], dtype=float32)

# Second: Using Classification Decision Tree After Modifying the Dataset

### Mapping the Dataset

In [39]:
#changing the chance of admition column into categorical data to apply classification decision tree
Admission_Predict_Dataset['Chance of Admit'] = np.where(Admission_Predict_Dataset['Chance of Admit'] < 0.75, 'No', 'Yes')
Admission_Predict_Dataset

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,Yes
1,2,324,107,4,4.0,4.5,8.87,1,Yes
2,3,316,104,3,3.0,3.5,8.00,1,No
3,4,322,110,3,3.5,2.5,8.67,1,Yes
4,5,314,103,2,2.0,3.0,8.21,0,No
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,Yes
396,397,325,107,3,3.0,3.5,9.11,1,Yes
397,398,330,116,4,5.0,4.5,9.45,1,Yes
398,399,312,103,3,3.5,4.0,8.78,0,No
399,400,333,117,4,5.0,4.0,9.66,1,Yes

### Splitting the Dataset into Features & Labels

In [40]:
features = Admission_Predict_Dataset.drop(['Chance of Admit','Serial No.'],axis=1)
labels = Admission_Predict_Dataset['Chance of Admit']

### Splitting the Dataset into Training, Testing, and Validation Data

In [41]:
features_train, features_validation_test, labels_train, labels_validation_test = train_test_split(
    features, labels, test_size=0.4, random_state=100)

In [42]:
features_validation, features_test, labels_validation, labels_test = train_test_split(
    features_validation_test, labels_validation_test, test_size=0.5, random_state=100)

In [43]:
print(len(features_train))
print(len(features_validation))
print(len(features_test))
print(len(labels_train))
print(len(labels_validation))
print(len(labels_test))

240
80
80
240
80
80

## Decision Tree (using max depth)

In [44]:
dt_classifier = DecisionTreeClassifier(max_depth=7)
dt_classifier.fit(features_train,labels_train)
cls_test_score=dt_classifier.score(features_test,labels_test)
cls_validation_score=dt_classifier.score(features_validation, labels_validation)
print(cls_test_score)
print(cls_validation_score)

0.7375
0.9

### Building a Predictive System

In [45]:
# predict

print(dt_classifier.predict([[335,115,4,5,4.5,9,1]]))

print(dt_classifier.predict([[310,100,3,2,3,8,0]]))

['Yes']
['No']

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [46]:
utils.display_tree(dt_classifier)

ModuleNotFoundError: No module named 'sklearn.externals.six'

## Decision Tree (using Gini index)

In [47]:
dt_classifier2 = DecisionTreeClassifier()
dt_classifier2.fit(features_train, labels_train)
cls_test_score2=dt_classifier2.score(features_test, labels_test)
cls_validation_score2=dt_classifier2.score(features_validation, labels_validation)
print(cls_test_score2)
print(cls_validation_score2)

0.725
0.875

### Building a Predictive System

In [48]:
# predict

print(dt_classifier2.predict([[335,115,4,5,4.5,9,1]]))

print(dt_classifier2.predict([[310,100,3,2,3,8,0]]))

['Yes']
['No']

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [49]:
utils.display_tree(dt_classifier2)

ModuleNotFoundError: No module named 'sklearn.externals.six'

## Decision Tree (using entropy index)

In [50]:
dt_classifier3 = DecisionTreeClassifier(criterion='entropy')
dt_classifier3.fit(features_train, labels_train)
cls_test_score3=dt_classifier3.score(features_test, labels_test)
cls_validation_score3=dt_classifier3.score(features_validation, labels_validation)
print(cls_test_score3)
print(cls_validation_score3)

0.6625
0.925

### Building a Predictive System

In [51]:
# predict

print(dt_classifier3.predict([[335,115,4,5,4.5,9,1]]))

print(dt_classifier3.predict([[310,100,3,2,3,8,0]]))

['Yes']
['No']

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

### Displaying the Decision Tree

In [52]:
utils.display_tree(dt_classifier3)

ModuleNotFoundError: No module named 'sklearn.externals.six'

# Additional: Using AdaBoost Method

In [53]:
!git clone https://github.com/s7s/machine_learning_1.git
%cd  machine_learning_1/ensemble_methods

e:\Courses\Software\AI\Array\Day25-MachineLearning\machine_learning_1\ensemble_methods

Cloning into 'machine_learning_1'...
C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [54]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import utils

from sklearn import tree

np.random.seed(0)

In [55]:
from sklearn.ensemble import AdaBoostClassifier
# Set the random_state so that we always get the same results
adaboost_classifier = AdaBoostClassifier(random_state=0, n_estimators=6)
adaboost_classifier.fit(features_train, labels_train)
adaboost_test_score=adaboost_classifier.score(features_test, labels_test)
adaboost_validation_score=adaboost_classifier.score(features_validation, labels_validation)
print(adaboost_test_score)
print(adaboost_validation_score)

0.8
0.95

C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(